// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $api_crawl from "./routes/api/crawl.ts";

import * as $index from "./routes/index.tsx";
import * as $WebCrawler from "./islands/WebCrawler.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/api/crawl.ts": $api_crawl,
    "./routes/api/screenshots.ts": $api_screenshots,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/WebCrawler.tsx": $WebCrawler,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
